### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by sunnykinger** [udithperera-dev/oneroot#1]
Hi, We desperately need a solution that can detect root on android devices. Is this solution production ready?

**Comment by udithperera-dev** [comment]
Hi,

Can i know who you are?

**Comment by sunnykinger** [comment]
App developer bro

**Comment by udithperera-dev** [comment]
yes, ios one still under development , but will rehearse soon

**Comment by sunnykinger** [comment]
For now I just needed to test the solution for android.
The solutions which already exist had 'false positive' issue.

**Comment by udithperera-dev** [comment]
i didnt understand

**Comment by sunnykinger** [comment]
I mean the existing solution is not accurate with detection. Many non-rooted devices are detected as rooted which causes problems.

**Comment by udithperera-dev** [comment]
a wait. within 2 days ill update that. give me that time period

Thankz for information

**Comment by udithperera-dev** [comment]
[fix added for wrong root detection issue for below android 9](https://github.com/udithperera-dev/oneroot/commit/b63f52c1c0232f7353c25f8035ced2e5cc8cc32c)
