### ISSUE TITLE
Error OneRoot.java:249: error: cannot find symbol KValidatorNative rootBeerNative = new KValidatorNative();

### ISSUE THREAD

**Issue by kauemurakami** [udithperera-dev/oneroot#3]
### Describe
I only add latest version of the package in my `package.yaml` and change my minSdk to 24, receive this error:
### Local variables
I using latest dart and latest flutter version with java 17
### Using to run
Tests in Pixel 5 and Xiaomi 13

```json
C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:245: error: package Build does not exist
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                     ^
C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
            KValidatorNative rootBeerNative = new KValidatorNative();
            ^
  symbol:   class KValidatorNative
  location: class OneRoot
C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
            KValidatorNative rootBeerNative = new KValidatorNative();
                                                  ^
  symbol:   class KValidatorNative
  location: class OneRoot
Note: C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Could you help me with this? tks

**Comment by udithperera-dev** [comment]
> ### Describe
> I only add latest version of the package in my `package.yaml` and change my minSdk to 24, receive this error:
> ### Local variables
> I using latest dart and latest flutter version with java 17
> ### Using to run
> Tests in Pixel 5 and Xiaomi 13
> 
> ```json
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:245: error: package Build does not exist
>         if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
>                                                      ^
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
>             KValidatorNative rootBeerNative = new KValidatorNative();
>             ^
>   symbol:   class KValidatorNative
>   location: class OneRoot
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
>             KValidatorNative rootBeerNative = new KValidatorNative();
>                                                   ^
>   symbol:   class KValidatorNative
>   location: class OneRoot
> Note: C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> ```
> 
> Could you help me with this? tks

Which android versions are in your devices?

**Comment by udithperera-dev** [comment]
> ### Describe
> I only add latest version of the package in my `package.yaml` and change my minSdk to 24, receive this error:
> ### Local variables
> I using latest dart and latest flutter version with java 17
> ### Using to run
> Tests in Pixel 5 and Xiaomi 13
> 
> ```json
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:245: error: package Build does not exist
>         if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
>                                                      ^
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
>             KValidatorNative rootBeerNative = new KValidatorNative();
>             ^
>   symbol:   class KValidatorNative
>   location: class OneRoot
> C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java:249: error: cannot find symbol
>             KValidatorNative rootBeerNative = new KValidatorNative();
>                                                   ^
>   symbol:   class KValidatorNative
>   location: class OneRoot
> Note: C:\Users\Kau�\AppData\Local\Pub\Cache\hosted\pub.dev\oneroot-0.1.3\android\src\main\java\com\akurupela\oneroot\core\OneRoot.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> ```
> 
> Could you help me with this? tks

Or sorry i got the issue? give me a moment, ill fix that!!! Also thank you for using this and notify me ✌️❤️

**Comment by kauemurakami** [comment]
thks, await your return !
Another thing that may be relevant is, even if I add other versions, deleting my pubspec.lock and the pub cache folder oneroot-0-1-3 it always takes me to the latest version

**Comment by udithperera-dev** [comment]
hi, I fixed , you can check, ext sorry for late !!!!

**Comment by udithperera-dev** [comment]
Thank you for your support !!! <3
