### ISSUE TITLE
Crashes on Android - NOT WORKING

### ISSUE THREAD

**Issue by ziyadmansy** [udithperera-dev/oneroot#4]
Error: package Build does not exist:

This error is likely due to a missing import statement for the [Build](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) class. The [Build](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) class is part of the Android OS and provides information about the current build, including the SDK version. The error message suggests that the compiler cannot find the [Build](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) class, which is usually due to the absence of an import statement for android.os.Build.

To resolve this error, ensure that the following import statement is present at the top of the OneRoot.java file:
`import android.os.Build;`

This import statement will make the Build class available in your code, allowing you to check the SDK version as intended.

**Comment by udithperera-dev** [comment]
ill add a fix soon !!, please show me the error or screenshot please

**Comment by ergarvitrai** [comment]
<img width="1440" alt="Screenshot 2024-09-02 at 3 59 22 PM" src="https://github.com/user-attachments/assets/e115900c-b3b2-42e1-9032-cc9123151633">
This is the error thrown when we are trying to run on android
It is happening in 0.1.4 too

**Comment by udithperera-dev** [comment]
Please add your fixes here, if you found 🙏

**Comment by udithperera-dev** [comment]
fixes added by community

**Comment by fourscience** [comment]
@udithperera-dev  Can you do a new release with these changes on pub.dev?

**Comment by udithperera-dev** [comment]
Do you have woking fixes, plz send me pr 🥹
